### ISSUE TITLE
conn.PingContext(ctx) returns error EOF

### ISSUE THREAD

**Issue by sebastianhoenig** [burningalchemist/sql_exporter#286] opened 2023-08-16 15:27 UTC
Hello,

Through multiple debug statements I have figured out that the database handle is successfully opened but the `conn.PingContext(ctx)` (https://github.com/burningalchemist/sql_exporter/blob/master/sql.go) returns the error EOF. I have read this is commonly associated with connections closing again, however I can't figure out when/how this may be happening.

The database is also not down as I can access it in a simple script just doing `conn.Query()` using the same go-ora driver. I also have not changed the global settings in the .yml file.

Some pointers in the right direction would be greatly appreciated!

Logs:

`ts=2023-08-16T14:26:34.855Z caller=klog.go:84 level=debug func=Infof msg="Database handle successfully openend with 'oracle' driver"`

`
ts=2023-08-16T14:26:35.078Z caller=klog.go:84 level=debug func=Infof msg="Error gathering metric: [from Gatherer #1] EOF"
`

**Comment by burningalchemist** [comment] 2023-08-17 09:08
Hey @sebastianhoenig, I've quickly run through the issue, also checked the library you're using. Could you also share the version of `go-ora` you embed? So far I can suggest several options (without having enough context):

- try to disable ping with `--config.enable-ping=false` in `sql_exporter`. Let's see what happens then.
- some folks here mention the EOF problem that's resolved by using `go-ora/v2`. I bet you're using this version, still adding the option for visibility.

Let me know, I think in the worst case, we can hop on a call, since it's a little bit tricky to reproduce the problem on my end (no access to OracleDB).

**Comment by sebastianhoenig** [comment] 2023-08-17 09:59
Thanks a lot for the reply! 

I am using `go-ora/v2` as you already guessed. 

Disabling ping now throws a new error. It probably has something to do with the Context? I am no go-programmer so just guessing here

`ts=2023-08-17T09:37:28.061Z caller=klog.go:84 level=debug func=Infof msg="Error gathering metric: [from Gatherer #1] [collector=\"oracle_test\", query=\"test\"] prepare query failed: EOF"`

**Comment by burningalchemist** [comment] 2023-08-17 16:09
Hey @sebastianhoenig, I don't think Context is an issue here as the same code works reliably for other database engines. One other guess I have is that we might be missing some connection parameters we need to pass in the DSN string. Could be some authentication-related stuff, ssl or nossl, etc. So whenever we don't meet the server requirements, it seems just cutting the connection. It might be that if you're using the database library directly, some parameters might be assumed.

I'm wondering how we can proceed on this issue further. Could you maybe share the script you've used to successfully query the db? Since it fails for ping and for running a query,  I'd say the issue more general as the server doesn't seem to want to communicate. I wish I got more details or log messages. As I offered we can proceed via email or can schedule a call, I'm happy to help.

**Comment by sebastianhoenig** [comment] 2023-08-22 12:01
Hey @burningalchemist, we have not fully figured it out yet, but it's definitely the go-driver that is the issue here. It requires an oracle wallet. 

Can close this for now I would say - thanks for the SSL hint!

**Comment by burningalchemist** [comment] 2023-08-22 12:05
Hey @sebastianhoenig, got it! Thanks for the info. 👍 Let me know if I can help somehow.
Wish I had a small instance per enterprise DB to test things better. 🤷‍♂️

**Closed as not planned by burningalchemist** 2023-08-22 12:05 UTC
Labels: question

**Comment by mateivladimir** [comment] 2024-03-06 10:27
Hey. I'm facing the same problem here. Do you have any solution ? Many thanks.

**Comment by burningalchemist** [comment] 2024-03-06 10:43
Hey @mateivladimir, Is your issue also related to `oracle` driver? I recommend to use `usql` (https://github.com/xo/usql) utility to investigate (it's more interactive), so you figure out the parameters expected, there might be some missing ones. This helped me multiple times. With proprietary DBs it's always tricky to debug unless there's some access to a database engine (I sadly don't have it).

**Comment by sebastianhoenig** [comment] 2024-03-06 13:59
Hey @mateivladimir - in our case the issue ended up being that we were using v1 instead of v2 of go-ora (even though I was initially convinced that I was using v2 already ;)). Re-checking the version again may just be the solution.

**Comment by mateivladimir** [comment] 2024-03-07 06:56
Many thanks for your comments. It seems to be right, i didnt upgrade to go-ora v2. I tried this and it works. Have a nice day :) !
